CREATE TABLE base_info
(
    base_info_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number                           VARCHAR(13),
    average_continuous_service_years_type      VARCHAR(255),
    average_continuous_service_years_Male      DOUBLE PRECISION,
    average_continuous_service_years_Female    DOUBLE PRECISION,
    average_continuous_service_years           DOUBLE PRECISION,
    average_age                                DOUBLE PRECISION,
    month_average_predetermined_overtime_hours DOUBLE PRECISION,
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)