CREATE TABLE business_item
(
    item_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number VARCHAR(13),
    item_type        VARCHAR(5),
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)