CREATE TABLE certification
(
    certification_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number       VARCHAR(13),
    date_of_approval       DATE,
    title                  VARCHAR(255),
    amount                 BIGINT,
    target                 VARCHAR(255),
    government_departments VARCHAR(255),
    category               VARCHAR(255),
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)