CREATE TABLE company
(
    corporate_number      VARCHAR(13) PRIMARY KEY NOT NULL UNIQUE,
    name                  VARCHAR(255),
    kana                  VARCHAR(255),
    name_en               VARCHAR(255),
    postal_code           VARCHAR(255),
    location              VARCHAR(255),
    process               VARCHAR(255),
    aggregated_year       VARCHAR(1),
    status                VARCHAR(255),
    close_date            DATE,
    close_status          VARCHAR(255),
    kind                  VARCHAR(10),
    representative_name   VARCHAR(255),
    capital_stock         BIGINT,
    employee_number       INTEGER,
    company_size_male     INTEGER,
    company_size_female   INTEGER,
    business_summary      TEXT,
    company_url           TEXT,
    founding_year         INTEGER,
    date_of_establishment DATE,
    qualification_grade   VARCHAR(255),
    update_date           TIMESTAMPTZ
)