CREATE TABLE finance
(
    finance_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number       VARCHAR(13),
    accounting_standards   VARCHAR(255),
    fiscal_year_cover_page TEXT,
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)