CREATE TABLE industry
(
    industry_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number VARCHAR(13),
    industry_type    VARCHAR(1),
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)