CREATE TABLE patent
(
    patent_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number    VARCHAR(13),
    patent_type         VARCHAR(255),
    registration_number VARCHAR(255),
    application_date    DATE,
    title               VARCHAR(255),
    url                 TEXT,
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)