CREATE TABLE procurement
(
    procurement_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number       VARCHAR(13),
    date_of_order          TIMESTAMPTZ,
    title                  VARCHAR(255),
    amount                 INTEGER,
    government_departments VARCHAR(255),
    note                   TEXT,
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)