CREATE TABLE women_activity_info
(
    women_activity_infos_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_info_id              INTEGER,
    female_workers_proportion_type VARCHAR(255),
    female_workers_proportion      DOUBLE PRECISION,
    female_share_of_manager        DOUBLE PRECISION,
    gender_total_of_manager        DOUBLE PRECISION,
    female_share_of_officers       DOUBLE PRECISION,
    gender_total_of_officers       DOUBLE PRECISION,
    FOREIGN KEY (workplace_info_id) REFERENCES workplace_info (workplace_info_id)
)