CREATE TABLE commendation
(
    commendation_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT,
    date_of_commendation   DATE,
    title                  VARCHAR(255),
    target                 TEXT,
    category               VARCHAR(255),
    government_departments VARCHAR(255),
    note                   TEXT,
    update_date            TIMESTAMPTZ,
    updated_at             TIMESTAMPTZ,
    inserted_at            TIMESTAMPTZ,
    FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE
);