CREATE TABLE compatibility_of_childcare_and_work
(
    compatibility_of_childcare_and_work_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_info_id                      INTEGER,
    number_of_paternity_leave              INTEGER,
    number_of_maternity_leave              INTEGER,
    paternity_leave_acquisition_num        INTEGER,
    maternity_leave_acquisition_num        INTEGER,
    FOREIGN KEY (workplace_info_id) REFERENCES workplace_info (workplace_info_id)
)