CREATE TABLE industry
(
    industry_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT,
    industry_type VARCHAR(1),
    FOREIGN KEY (company_id) REFERENCES company (company_id)
);