CREATE TABLE procurement
(
    procurement_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT,
    date_of_order          TIMESTAMPTZ,
    title                  VARCHAR(255),
    amount                 BIGINT,
    government_departments VARCHAR(255),
    note                   TEXT,
    FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE
);