CREATE TABLE business_item
(
    item_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER,
    item_type  VARCHAR(5),
    FOREIGN KEY (company_id) REFERENCES company (company_id)
)