CREATE TABLE commendation
(
    commendation_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER,
    date_of_commendation   DATE,
    title                  VARCHAR(255),
    target                 VARCHAR(255),
    category               VARCHAR(255),
    government_departments VARCHAR(255),
    note                   TEXT,
    FOREIGN KEY (company_id) REFERENCES company (company_id)
)