CREATE TABLE finance
(
    finance_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER,
    accounting_standards   VARCHAR(255),
    fiscal_year_cover_page TEXT,
    FOREIGN KEY (company_id) REFERENCES company (company_id)
)