CREATE TABLE patent
(
    patent_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER,
    patent_type         VARCHAR(255),
    registration_number VARCHAR(255),
    application_date    DATE,
    title               TEXT,
    url                 TEXT,
    FOREIGN KEY (company_id) REFERENCES company (company_id)
)