CREATE TABLE subsidy
(
    subsidy_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER,
    date_of_approval       DATE,
    title                  VARCHAR(255),
    amount                 BIGINT,
    target                 VARCHAR(255),
    government_departments VARCHAR(255),
    FOREIGN KEY (company_id) REFERENCES company (company_id)
)