CREATE TABLE workplace_info
(
    workplace_info_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corporate_number  VARCHAR(13),
    FOREIGN KEY (corporate_number) REFERENCES company (corporate_number)
)