spring.application.name=gBizINFO JSON Importer
apiToken=${API_TOKEN}
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
logging.level.com.java.gbizinfo=DEBUG

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.java.gbizinfo.importer.model

#local-path=src/main/resources/zip/Hojinjoho_20260306
#app.importer.url="https://info.gbiz.go.jp/hojin/Download";
app.importer.url = rtrtrtrtrt
local-path=ffhffhfh

app.importer.zone=Europe/Chisinau
app.importer.probe-delay-ms=30000
app.importer.windows=night=00:00-07:00,day=08:00-10:00

#app.importer.source=remote
app.importer.source = local
