spring.application.name=gBizINFO JSON Importer
apiToken=${API_TOKEN}
spring.datasource.url=jdbc:postgresql://localhost:5432/company_info
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false
logging.level.com.java.gbizinfo=DEBUG

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:mapper/**/*.xml
mybatis.type-aliases-package=com.java.gbizinfo.importer.model