CREATE TABLE base_info
(
    base_info_id                               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workplace_info_id                          BIGINT,
    average_continuous_service_years_type      VARCHAR(255),
    average_continuous_service_years_male      DOUBLE PRECISION,
    average_continuous_service_years_female    DOUBLE PRECISION,
    average_continuous_service_years           DOUBLE PRECISION,
    average_age                                DOUBLE PRECISION,
    month_average_predetermined_overtime_hours DOUBLE PRECISION,
    updated_at                                 TIMESTAMPTZ,
    inserted_at                                TIMESTAMPTZ,
    FOREIGN KEY (workplace_info_id) REFERENCES workplace_info (workplace_info_id) ON DELETE CASCADE
);