CREATE TABLE classification
(
    classification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patent_id         BIGINT,
    code_value        VARCHAR(255),
    code_name         VARCHAR(255),
    japanese          VARCHAR(255),
    FOREIGN KEY (patent_id) REFERENCES patent (patent_id) ON DELETE CASCADE
);
