CREATE TABLE major_shareholder
(
    major_shareholder_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finance_id              BIGINT,
    name_major_stakeholders VARCHAR(255),
    shareholding_ratio      DOUBLE PRECISION,
    FOREIGN KEY (finance_id) REFERENCES finance (finance_id)
);